from tkinter import *

window = Tk()
window.title("Calculator")
window.geometry('320x480')
window.configure(bg="#282828")

def hello():
    print("hai")
button_1 = Button(window, text ="1",padx=20,pady=20, command = hello)
button_2 = Button(window, text ="2",padx=20,pady=20, command = hello)
button_3 = Button(window, text ="3",padx=20,pady=20, command = hello)
button_4 = Button(window, text ="4",padx=20,pady=20, command = hello)
button_5 = Button(window, text ="5",padx=20,pady=20, command = hello)
button_6 = Button(window, text ="6",padx=20,pady=20, command = hello)
button_7 = Button(window, text ="7",padx=20,pady=20, command = hello)
button_8 = Button(window, text ="8",padx=20,pady=20, command = hello)
button_9 = Button(window, text ="9",padx=20,pady=20, command = hello)
button_0 = Button(window, text ="0",padx=20,pady=20, command = hello)
button_1.grid(row=1,column=1)
button_2.grid(row=1,column=2)
button_3.grid(row=1,column=3)
button_4.grid(row=2,column=1)
button_5.grid(row=2,column=2)
button_6.grid(row=2,column=3)
button_7.grid(row=3,column=1)
button_8.grid(row=3,column=2)
button_9.grid(row=3,column=3)
button_0.grid(row=4,column=2)
mainloop()