from tkinter import *

window = Tk()
window.title("Calculator")
window.geometry('320x480')
window.configure(bg="#282828")

escreen = Entry(window, width=35)
escreen.grid(row=0, column=0, columnspan=3, padx=20, pady=10)

def hello():
    print("hai")
button_1 = Button(window, text ="1",padx=20,pady=20, command = hello)
button_2 = Button(window, text ="2",padx=20,pady=20, command = hello)
button_3 = Button(window, text ="3",padx=20,pady=20, command = hello)
button_4 = Button(window, text ="4",padx=20,pady=20, command = hello)
button_5 = Button(window, text ="5",padx=20,pady=20, command = hello)
button_6 = Button(window, text ="6",padx=20,pady=20, command = hello)
button_7 = Button(window, text ="7",padx=20,pady=20, command = hello)
button_8 = Button(window, text ="8",padx=20,pady=20, command = hello)
button_9 = Button(window, text ="9",padx=20,pady=20, command = hello)
button_0 = Button(window, text ="0",padx=20,pady=20, command = hello)
button_dot = Button(window, text =".",padx=20,pady=20, command = hello)
# button_del = Button(window, text ="DEL",padx=20,pady=20, command = hello)
button_del = Button(window, text ="del",padx=20,pady=20, command = hello)
button_plus = Button(window, text ="+",padx=20,pady=20, command = hello)
button_sub = Button(window, text ="-",padx=20,pady=20, command = hello)
button_mul = Button(window, text ="*",padx=20,pady=20, command = hello)
button_div = Button(window, text ="/",padx=20,pady=20, command = hello)

button_1.grid(row=9,column=0)
button_2.grid(row=9,column=1)
button_3.grid(row=9,column=2)
button_4.grid(row=10,column=0)
button_5.grid(row=10,column=1)
button_6.grid(row=10,column=2)
button_7.grid(row=11,column=0)
button_8.grid(row=11,column=1)
button_9.grid(row=11,column=2)
button_dot.grid(row=12,column=0)
button_0.grid(row=12,column=1)
button_del.grid(row=12,column=2)
button_plus.grid(row=9,column=4)
button_sub.grid(row=10,column=4)
button_mul.grid(row=11,column=4)
button_div.grid(row=12,column=4)
mainloop()